version: '3'

tasks:
  install-tools:
    desc: "Installs local workstation tools"
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.0.2
      - go install github.com/goreleaser/goreleaser@latest
      - go install github.com/securego/gosec/v2/cmd/gosec@latest

  lint:
    desc: "Run gofmt, govet and golangci-lint"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run ./...

  lint-fix:
    desc: "Run gofmt, govet and golangci-lint, fixing errors as well"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run ./... --fix

  security:
    desc: "Run gosec for security analysis"
    cmds:
      - gosec ./...

  test:
    desc: "Run unit tests"
    cmds:
      - go test -v ./...
