name: CI

on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: '1.22'

jobs:
  install-tools:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install golangci-lint, goreleaser, and gosec
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.0.2
          go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run lint
        run: |
          go fmt ./...
          go vet ./...
          golangci-lint run ./...

      - name: Run gosec for security analysis
        run: |
          gosec ./...

      - name: Run unit tests
        run: |
          go test -v ./...
