name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GO_VERSION: '1.22'  # Set Go version here

jobs:
  install-tools:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install golangci-lint, goreleaser, and gosec
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.0.2
          go install github.com/securego/gosec/v2/cmd/gosec@latest

  publish:
    runs-on: ubuntu-latest
    needs: install-tools
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.ref =~ /^refs\/tags\/v\d+\.\d+\.\d+$/  # Match vX.X.X pattern

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Tagging version
        run: |
          echo "Tagging version ${{ github.ref }}"
          git tag ${{ github.ref }}
          git push origin ${{ github.ref }}

      - name: Publish Go module
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/gonfidel/syncret@${{ github.ref }}
