name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GO_VERSION: '1.22'  # Set Go version here

jobs:
  pipelines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install golangci-lint, goreleaser, and gosec
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.0.2
          go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run lint
        run: |
          go fmt ./...
          go vet ./...
          golangci-lint run ./...

      - name: Run gosec for security analysis
        run: |
          gosec ./...

      - name: Run unit tests
        run: |
          go test -v ./...

      - name: Run gosec for security analysis
        run: |
          gosec ./...

      - name: Publish Go module
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/gonfidel/syncret@${{ github.ref_name }}
